name: Webpack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: install
      run: yarn install
    - name: build
      run: yarn run webpack

    - name: add nojekyll
      run: touch ./dist/.nojekyll
      
    - name: index.html
      run: cp index.html dist/index.html

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
